# GAK_PENTING
CLIENT_PORT = 1920
SERVER_PORT = 1356  #gabutuh tapi dokumentasi aja
                    #SOALNYA ADA YANG JANJI DATENG JAM 13.00

LOCAL_IP = "localhost"
SOCKET_TIMEOUT = 5

SEGMENT_SIZE = 32768
SEGMENT_DATA_SIZE = 32756
WINDOW_SIZE = 10