# GAK_PENTING
CLIENT_PORT = 1920
SERVER_PORT = 1356  #gabutuh tapi dokumentasi aja
                    #SOALNYA ADA YANG JANJI DATENG JAM 13.00

LOCAL_IP = "localhost"
TRANSFER_TIMEOUT = 0.5
LISTEN_TRANSFER_TIMEOUT = 0.5
ACK_TIMEOUT = 1
SERVER_TIMEOUT = 2

SEGMENT_SIZE = 32768
SEGMENT_DATA_SIZE = 32756
WINDOW_SIZE = 10